PAYMENT_STATUS_PENDING = "P"
PAYMENT_STATUS_COMPLETE = "C"
PAYMENT_STATUS_FAILED = "F"

PAYMENT_STATUS_CHOICES = [
    (PAYMENT_STATUS_PENDING, "Pending"),
    (PAYMENT_STATUS_COMPLETE, "Complete"),
    (PAYMENT_STATUS_FAILED, "Failed"),
]
